name: Deploy CD

# GitHub variables:
# - VERSION_TAG
# - ASTRO_SITE_URL
# - ASTRO_BASE_PATH
# - ASTRO_ASSETS_PREFIX

# GitHub secrets:
# - CONFIG_PROD (optional)

on:

  # Run on push on production branches
  push:
    branches:
      # Production
      - main
    paths:
      # CI/CD files
      - '.github/workflows/deploy.yml'
      - 'docker-compose.yml'
      - 'docker-compose.cicd.yml'
      - '.env'
      # Application files
      - 'app/**'

  # Run on manual triggers
  workflow_dispatch:

# Set default GITHUB_TOKEN permissions for the workflow
permissions:
  contents: read

# Set workflow concurrency rules
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  # Build job
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      # Dependency steps

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          # apt-get install jq
          sudo apt-get -q update
          sudo apt-get -qy install --no-install-recommends jq

      # Preparation steps

      - name: Load app config in environment
        env:
          GITHUB_VARS: ${{ toJson(vars) }}
          CONFIG_PROD: ${{ secrets.CONFIG_PROD }}
        run: |
          # Load app config in environment

          load_var() {

            local var_name="$1"
            local fallback_github_vars="$2"

            if [ -z "${var_name}" ]; then
              echo "ERROR: Variable name is empty" >&2
              return 1
            fi

            # Check if the variable is set in CONFIG_PROD
            local var_value=$(echo "${CONFIG_PROD}" | jq -rcM --arg var_name "${var_name}" '.[$var_name]')
            if [ -z "${var_value}" ] || [ "${var_value}" = "null" ]; then
              echo "INFO: Variable '${var_name}' not found in CONFIG_PROD" >&2

              if [ "${fallback_github_vars}" != 'true' ]; then
                return 0
              fi

              # Check if the variable is set in GITHUB_VARS
              var_value=$(echo "${GITHUB_VARS}" | jq -rcM --arg var_name "${var_name}" '.[$var_name]')
              if [ -z "${var_value}" ] || [ "${var_value}" = "null" ]; then
                echo "INFO: Variable '${var_name}' not found in GITHUB_VARS" >&2
                return 0
              fi
            fi

            if [ -n "${var_value}" ]; then
              echo "${var_value}" | sed 's/^ */::add-mask::/'
            fi
            echo "Set ${var_name} (secret)"
            echo "${var_name}<<GITHUB_ENV_EOF" >> "$GITHUB_ENV"
            echo "${var_value}" >> "$GITHUB_ENV"
            echo 'GITHUB_ENV_EOF' >> "$GITHUB_ENV"
          }

          echo '::group::Load app config variables'

          # Deployment
          load_var 'VERSION_TAG' 'true'

          # Astro
          load_var 'ASTRO_SITE_URL' 'true'
          load_var 'ASTRO_BASE_PATH' 'true'
          load_var 'ASTRO_ASSETS_PREFIX' 'true'

          # Application
          # (Load env vars for your application here.)

          echo '::endgroup::'

      # Execution steps

      - name: Pull dependencies
        run: |
          # docker compose pull --ignore-buildable
          docker compose \
            -f ./docker-compose.yml -f ./docker-compose.cicd.yml \
            --env-file .env \
            pull --ignore-buildable

      - name: Build for production
        env:
          # Build
          BUILD_CHECK: 'false' # Skip type checks
          # Deployment
          GITHUB_REPOSITORY_URL: https://github.com/${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          VERSION_TAG: ${{ env.VERSION_TAG }}
          # Astro
          ASTRO_SITE_URL: ${{ env.ASTRO_SITE_URL }}
          ASTRO_BASE_PATH: ${{ env.ASTRO_BASE_PATH }}
          ASTRO_ASSETS_PREFIX: ${{ env.ASTRO_ASSETS_PREFIX }}
          # Application
          # (Add env vars for your application here.)
        run: |
          # docker compose build
          export DOCKER_UID="$(id -u)"
          docker compose \
            -f ./docker-compose.yml -f ./docker-compose.cicd.yml \
            --env-file .env \
            build

      - name: Copy application files
        run: |
          # docker compose up
          export DOCKER_UID="$(id -u)"
          docker compose \
            -f ./docker-compose.yml -f ./docker-compose.cicd.yml \
            --env-file .env \
            up

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./app/dist

  # Deploy job
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Job dependencies
    needs:
      - build

    # Set GITHUB_TOKEN permissions for the job
    permissions:
      id-token: write
      pages: write

    # Set deployment environment
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # Execution steps

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
